linters:
  enable-all: true
  disable:
    - godot
    - gci
    - funlen
    - wrapcheck
    - varnamelen
    - paralleltest
    - ireturn
    - gomnd
    - thelper
    - tagliatelle
    - noctx
    - nlreturn
    - wsl
    - err113
    - gochecknoglobals
    - exhaustruct
    - nolintlint
    - maintidx
    - misspell
    - dupword
    - depguard
    - execinquery
    - protogetter
    - mnd
    - inamedparam
    - testifylint
    - perfsprint
    - contextcheck
    - revive
linters-settings:
  cyclop:
    max-complexity: 10
    package-average: 0
    skip-tests: true
