linters:
  enable-all: true
  disable:
    - godot
    - gci
    - funlen
    - maligned
    - golint
    - scopelint
    - interfacer
    - wrapcheck
    - varnamelen
    - paralleltest
    - ireturn
    - gomnd
    - thelper
    - tagliatelle
    - noctx
    - nlreturn
    - exhaustivestruct
    - wsl
    - goerr113
    - gochecknoglobals
    - exhaustruct
    - nolintlint
    - maintidx
    - misspell
    - dupword
linters-settings:
  cyclop:
    max-complexity: 10
    package-average: 0
    skip-tests: true
