version: "2"
linters:
  default: all
  disable:
    - depguard
    - dupword
    - err113
    - exhaustruct
    - funcorder
    - funlen
    - gochecknoglobals
    - godot
    - inamedparam
    - ireturn
    - maintidx
    - misspell
    - mnd
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - protogetter
    - tagliatelle
    - testifylint
    - thelper
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    cyclop:
      max-complexity: 10
      package-average: 0
    staticcheck:
      checks:
        - all
        - '-QF1008'  # "could remove embedded field "..." from selector"
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - cyclop
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
